# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d8788926a9a68368a72573ef0392b522feef50d8100d957878f519d82f019dffce4500d92a54204db7005e6ed07d88934297527083831281a42598adaadd2e1

test:
  secret_key_base: 0a27e8b275474518e9a398de25cb6ef09dfb6944359e8b9b3a97b40874e127649925edd674d9d3f5d3e686fa26759c79c4cdb4f284d0cb6ae94f7fe992336650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
